### ISSUE TITLE
inappropriate function call

### ISSUE THREAD

**Issue by ptrav1956** [xively/xively_arduino#12]
When trying to compile to connect through a WiFly shield, I have the code as given for the WiFly shield in the README, namely

``` C
WiFlyClient client;
XivelyClient xivelyclient(client);
```

then I get a number of errors.  The first is because the WiFlyClient declaration from the Sparkfun library expects a destination and a port

If I replace this with 

``` C
WiFlyClient client("api.xively.com",80);
XivelyClient xivelyclient(client);
```

 then I get the error

> ```
> Xively_sketch_aug20a:57: error: no matching function for call to 'XivelyClient::XivelyClient(WiFlyClient&)'
> /Users/paultravers/Documents/Arduino/libraries/xively/XivelyClient.h:11: note: candidates are: XivelyClient::XivelyClient(Client&)
> /Users/paultravers/Documents/Arduino/libraries/xively/XivelyClient.h:9: note:                 XivelyClient::XivelyClient(const XivelyClient&)
> ```

which appears to suggest that the declaration of the client type in the first statement is incompatible with the datatype required in the second statement.  I am sure there is a solution for this but can't find it myself.

**Comment by errordeveloper** [comment]
@ptrav1956 you are absolutely welcome to fork and send us a pull request to fix this part of documentation.
However, the WiFly shields are not officially support as there various issue with drivers and the hardware itself.
As far as I know, there exist multiple version of WiFly driver, and one of them should work the way we have documented this. I am not sure which one that would and, as I said, it's not officially support. Therefore, I will close this issue. You may attempt asking on either [StackOverflow](http://stackoverflow.com/questions/tagged/arduino) or [Arduino Forums](http://arduino.cc/forum).
