### ISSUE TITLE
Make library easier to install in Arduino IDE

### ISSUE THREAD

**Issue by alxmjo** [xively/xively_arduino#18]
The library can't simply be downloaded and installed to the Arduino IDE because the filename isn't accepted. So, a user must download, unzip, and then change the name of the folder that contains the library files. This isn't a huge burden, but it'd be easy to fix. Just change the name of the folder to "Xively" instead of "xively_arduino-master" so that when someone downloads it they can install it straight away without any error messages.

![screen shot 2014-06-05 at 11 40 10 am](https://cloud.githubusercontent.com/assets/1656106/3185002/42e5a08c-ec8d-11e3-8469-891d66f6f114.png)
![screen shot 2014-06-05 at 11 39 49 am](https://cloud.githubusercontent.com/assets/1656106/3185005/45e119e2-ec8d-11e3-997d-e02d2fb6f2af.png)

**Comment by Alienwaren** [comment]
I have this issue too. But they can't do anything - the name is generated by Github, the Arduino IDE have problems imo.
