### ISSUE TITLE
Getting various error codes from WiFiMultipleDatastreamsUpload example

### ISSUE THREAD

**Issue by errordeveloper** [xively/xively_arduino#3]
**_Originally reported as cosm/cosm-arduino#11 by @mcdonaldajr.**_

Using standard Arduino with standard Wireless Shield.

Opened example and added SSID, password, API key and feed ID. Changed nothing else.
When run, COSM returns various error codes, plus sometimes 200, indicating success.
Error codes: -3, -4, -411. Estimate less than 50% return success (200).

Output log:

```
Starting multiple datastream upload to Cosm...

Attempting to connect to SSID: BTHomeHub2-7PT7
Connected to wifi
SSID: BTHomeHub2-7PT7
IP Address: 192.168.1.90
signal strength (RSSI):-31 dBm
Read sensor value 608.00
Setting buffer value to:
    a message to upload
Setting string value to:
    7 is a random number
Uploading it to Cosm
cosmclient.put returned 200

Read sensor value 504.00
Setting buffer value to:
    a message to upload
Setting string value to:
    49 is a random number
Uploading it to Cosm
cosmclient.put returned 200

Read sensor value 515.00
Setting buffer value to:
    a message to upload
Setting string value to:
    73 is a random number
Uploading it to Cosm
cosmclient.put returned -411

Read sensor value 519.00
Setting buffer value to:
    a message to upload
Setting string value to:
    58 is a random number
Uploading it to Cosm
cosmclient.put returned -3

Read sensor value 527.00
Setting buffer value to:
    a message to upload
Setting string value to:
    30 is a random number
Uploading it to Cosm
cosmclient.put returned -411

Read sensor value 533.00
Setting buffer value to:
    a message to upload
Setting string value to:
    72 is a random number
Uploading it to Cosm
cosmclient.put returned 200

Read sensor value 534.00
Setting buffer value to:
    a message to upload
Setting string value to:
    44 is a random number
Uploading it to Cosm
cosmclient.put returned 200

Read sensor value 535.00
Setting buffer value to:
    a message to upload
Setting string value to:
    78 is a random number
Uploading it to Cosm
cosmclient.put returned -4

Read sensor value 533.00
Setting buffer value to:
    a message to upload
Setting string value to:
    23 is a random number
Uploading it to Cosm
cosmclient.put returned -3

Read sensor value 525.00
Setting buffer value to:
    a message to upload
Setting string value to:
    9 is a random number
Uploading it to Cosm
cosmclient.put returned 200

Read sensor value 521.00
Setting buffer value to:
    a message to upload
Setting string value to:
    40 is a random number
Uploading it to Cosm
cosmclient.put returned -411
```

**Comment by chut** [comment]
@mcdonaldajr Did you ever find a solution to this problem? I've seen similar issues cause by the Arduino Wifi shield itself. The first thing I would recommend is updating the firmware on your WiFi shield. Arduino has the instructions [here](http://arduino.cc/en/Hacking/WiFiShieldFirmwareUpgrading).

**Comment by mcdonaldajr** [comment]
@chut 
I had to resort to single stream upload, which works OK. I recently tried updating to the latest WiFi firmware and Arduino software, but like many others, I can't get the shield to work even with the simplest of examples, so have reverted back to the older software and firmware.

**Comment by OricTosh** [comment]
This might be totally off the mark as it was with a Ethernet Shield rather than WiFi. I kept losing my IP address was the symptom I was having with LCD, Ethernet, Duemilanove setup with multiple upload stream which was caused by having some pins from the LCD plugged into the SPI data bus pins needed by the shield i.e. pins D10, D11, D12, D13. Moved the conflicting connections from the display to other pins and all was well.

**Comment by errordeveloper** [comment]
@OricTosh that's off-topic here, sounds like a hardware issue.

**Comment by errordeveloper** [comment]
@mcdonaldajr Okay, have you tried doing anything else with this shield, i.e. may be run some web server example and see if it responds consistently? There could be some odd issue with WLAN, I'd try on a different network also.

**Comment by OricTosh** [comment]
@errordeveloper http://arduino.cc/en/Main/ArduinoWiFiShield <--- believe this is the one being used by @mcdonaldajr the shield uses SPI to talk to the Arduino, in fact the same as the Ethernet shield; SPI on digital pins 11, 12, and 13 on the Uno  

``` C
// default Arduino sketch for a LCD 16x2 Display 
#include <LiquidCrystal.h>

LiquidCrystal lcd(12, 11, 10, 5, 4, 3, 2);

void setup()
{
  lcd.print("hello, world!");
}

void loop() {}
```

So if you use a default example setting up a LCD display and your using an WiFi/Ethernet Shield the LCD pins conflict with the SPI bus being used by the shield. So my point is how can you say that my response is a hardware issue when I can change the setup for the LCD in the in the program code. The software `LiquidCrystal lcd (8, 9, 10, 5, 4, 3, 2)`
@mcdonaldajr description showed similar errors as not getting the correct response 200 when uploading data
I used this library and thought he/she might have done the same and making the above change enable me to use this library with an LCD and Ethernet Shield. As you see here https://plus.google.com/u/0/106191182717678017250/posts it's the top left

**Comment by errordeveloper** [comment]
@OricTosh seems like #2 is all about the same thing...

**Comment by errordeveloper** [comment]
I am closing this as it's not related to library code, please refer to [StackOverflow](http://stackoverflow.com/questions/tagged/arduino) or [Arduino Forums](http://arduino.cc/forum).
