### ISSUE TITLE
Web front for Xively + Arduino

### ISSUE THREAD

**Issue by roquito** [xively/xively_arduino#5]
Hi all, I am a noob here so thanks in advance for the support. I have now made Arduino and Xively talk to each other just fine. Now, I would like to have a web app where I can display the information read from sensors on the Arduino but don't know what solution is the best out there. I don't necessarily wish to have to learn a new language so I can program this. Ideally, this could be done with a simple app/solution that I can send Xively API commands back and forth with. Can someone point me in the right direction or provide help?

**Comment by dox** [comment]
There is an 'API Endpoint' that you can use for each feed (listed at the top of your feed page).  This can return your data in json, xml or csv.
It's pretty well documented here: https://xively.com/dev/docs/api/data/read/single_feed/

**Comment by frasermac** [comment]
@Roquito Try out a simple JavaScript app that is included with the Xively JavaScript library - http://xively.github.io/xively-js/tutorial/ - the demo app sounds like what you're looking for!

Also, for questions like this that aren't exactly issues with the Arduino library, a good place to get help is on a forum just for the purpose - see [Xively Help](xively.com/dev/help)
